# This file was generated by GoReleaser. DO NOT EDIT.
cask "inngest" do
  version "1.41.1"

  on_macos do
    on_intel do
      sha256 "a5595ec2a8cc99af99b3622ae0354d3d5e2f04aae1f30133134c29616141eb65"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6c0c4e923b1bb4a09696ca31b919b1980b7e8c06f7612d2e6d7b58d0df1b7ce6"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "406737e04c2221697448d0d0b9d4742570b7dafef1b0bcfbf1eed14e0f957428"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bf970fc6109c35c2bbe99763d037011919fe0d6809a769231800a9a5cd8d51f"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_linux_arm64.tar.gz"
    end
  end

  name "inngest"
  desc "Inngest CLI and development server"
  homepage "https://www.inngest.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inngest"

  # No zap stanza required

end
