# This file was generated by GoReleaser. DO NOT EDIT.
cask "inngest" do
  version "1.38.0"

  on_macos do
    on_intel do
      sha256 "0c0259528e4486d9fc01e05b4afabdcf57bbb9853b6e665d2520c4444401cdfe"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6766270b508109b97d97571cf059f0656803453a741a7599aa4ee8baffb15f0"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de8df6e375471f9fe17a700a7774ab072785bb5410f5a2daf2f456b020d46725"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0079bab9734479bafcac987ce096f25c45f650c773edaf81c5e957578d576940"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_linux_arm64.tar.gz"
    end
  end

  name "inngest"
  desc "Inngest CLI and development server"
  homepage "https://www.inngest.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inngest"

  # No zap stanza required

end
