# This file was generated by GoReleaser. DO NOT EDIT.
cask "inngest" do
  version "1.43.0"

  on_macos do
    on_intel do
      sha256 "3fbe7c4667bebe55c9db1dad8ccb655e08c9393f2e77a13de74a49d12759dd94"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a51781ad81f5b628e99ae454b5d0375b0ab677c07dc30334c770b1e3382bda3"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ef689731c7fa599078a57a1533a34dc88a66ec2d21fedce9270be473172abbd"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "219e974121641c30db0746565eb9466c0c96dcbd22f5c5d77f96105926ca2102"
      url "https://github.com/inngest/inngest/releases/download/v#{version}/inngest_#{version}_linux_arm64.tar.gz"
    end
  end

  name "inngest"
  desc "Inngest CLI and development server"
  homepage "https://www.inngest.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inngest"

  # No zap stanza required

end
